import { db } from "./db";
import { clubs } from "@shared/schema";
import { log } from "./index";

const SEED_CLUBS = [
  {
    name: "Tirumala Trekkers",
    category: "Trekking",
    emoji: "🏔️",
    bgColor: "#e8f4e8",
    shortDesc: "Weekly treks around Tirumala hills and Eastern Ghats. All fitness levels welcome.",
    fullDesc: "We've been trekking together since 2022. Every Sunday morning we hit a new trail — from Tirumala Ghat roads to Talakona, Gunjana, and Kapila Theertham. We go at the slowest person's pace. Beginners always welcome.",
    organizerName: "Ravi Kumar",
    organizerYears: "3 years running",
    organizerAvatar: "👨‍🦱",
    organizerResponse: "Responds within 2 hrs",
    memberCount: 84,
    schedule: "Every Sunday, 5:30 AM",
    location: "Alipiri Gate",
    activeSince: "2022",
    whatsappNumber: "919000000001",
    healthStatus: "green",
    healthLabel: "Very Active",
    lastActive: "Met last Sunday",
    foundingTaken: 16,
    foundingTotal: 20,
    timeOfDay: "morning",
  },
  {
    name: "Tirupati Reads",
    category: "Books",
    emoji: "📚",
    bgColor: "#fef9e7",
    shortDesc: "Monthly book club for fiction, non-fiction, and Telugu literature lovers.",
    fullDesc: "Started by a group of college friends, Tirupati Reads has grown into a warm community of 50+ book lovers. We read one book a month, meet at a local café, and genuinely argue about whether the ending was worth it. Telugu and English books both welcome.",
    organizerName: "Priya Sharma",
    organizerYears: "2 years running",
    organizerAvatar: "👩",
    organizerResponse: "Responds within 4 hrs",
    memberCount: 52,
    schedule: "First Saturday, 6:00 PM",
    location: "Café Tirupati, TP Area",
    activeSince: "2023",
    whatsappNumber: "919000000002",
    healthStatus: "green",
    healthLabel: "Very Active",
    lastActive: "Met last Saturday",
    foundingTaken: 11,
    foundingTotal: 20,
    timeOfDay: "evening",
  },
  {
    name: "Tirupati Cyclists",
    category: "Cycling",
    emoji: "🚴",
    bgColor: "#e8f0fe",
    shortDesc: "Early morning rides through Tirupati city and surrounding villages. All bikes welcome.",
    fullDesc: "We ride every Saturday and Sunday at 5:45 AM from RTC Bus Stand. Routes from 20km to 60km. Road bikes, MTBs, and hybrids all welcome. Safety first — helmet always required, no exceptions.",
    organizerName: "Suresh Reddy",
    organizerYears: "4 years running",
    organizerAvatar: "👨",
    organizerResponse: "Responds within 1 hr",
    memberCount: 67,
    schedule: "Sat & Sun, 5:45 AM",
    location: "RTC Bus Stand",
    activeSince: "2021",
    whatsappNumber: "919000000003",
    healthStatus: "green",
    healthLabel: "Very Active",
    lastActive: "Rode yesterday",
    foundingTaken: 14,
    foundingTotal: 20,
    timeOfDay: "morning",
  },
  {
    name: "Lens & Light Tirupati",
    category: "Photography",
    emoji: "📷",
    bgColor: "#f3e8ff",
    shortDesc: "Photography walks around Tirupati's temples, markets, and nature spots.",
    fullDesc: "Monthly photo walks plus editing workshops and print exhibitions. From phone cameras to DSLRs — all are welcome. Tirumala at dawn, Govindaraja Swamy temple at golden hour, the chaos of Balaji Nagar market — Tirupati is full of frames waiting to be captured.",
    organizerName: "Anitha Devi",
    organizerYears: "2 years running",
    organizerAvatar: "👩‍🦱",
    organizerResponse: "Responds within 6 hrs",
    memberCount: 39,
    schedule: "2nd Sunday, 6:00 AM",
    location: "Govindaraja Temple Gate",
    activeSince: "2023",
    whatsappNumber: "919000000004",
    healthStatus: "yellow",
    healthLabel: "Moderate",
    lastActive: "Met 2 weeks ago",
    foundingTaken: 8,
    foundingTotal: 20,
    timeOfDay: "morning",
  },
  {
    name: "Tirupati Fitness Tribe",
    category: "Fitness",
    emoji: "💪",
    bgColor: "#fde8e8",
    shortDesc: "Outdoor bootcamp, yoga, and running. Free community fitness for all ages.",
    fullDesc: "We meet at Bairagipatteda Park every morning at 6 AM. Bootcamp on Monday-Wednesday-Friday, yoga on Tuesday-Thursday, and group runs on Saturday. All ages and levels welcome. No equipment needed, just show up ready to move.",
    organizerName: "Suresh Babu",
    organizerYears: "5 years running",
    organizerAvatar: "🧔",
    organizerResponse: "Responds within 1 hr",
    memberCount: 120,
    schedule: "Mon-Sat, 6:00 AM",
    location: "Bairagipatteda Park",
    activeSince: "2020",
    whatsappNumber: "919000000005",
    healthStatus: "green",
    healthLabel: "Very Active",
    lastActive: "Met this morning",
    foundingTaken: 20,
    foundingTotal: 20,
    timeOfDay: "morning",
  },
  {
    name: "Telugu Writers Circle",
    category: "Books",
    emoji: "✍️",
    bgColor: "#fff3e0",
    shortDesc: "For aspiring Telugu writers — poetry, short stories, and essays.",
    fullDesc: "Share your work in a safe, encouraging space. Monthly anthology publications and open mic events. Whether you write in Telugu or English, if you love putting words on paper, this is your tribe. We celebrate every voice.",
    organizerName: "Lakshmi Naidu",
    organizerYears: "1 year running",
    organizerAvatar: "👩‍🏫",
    organizerResponse: "Responds within 8 hrs",
    memberCount: 28,
    schedule: "3rd Sunday, 4:00 PM",
    location: "District Library",
    activeSince: "2024",
    whatsappNumber: "919000000006",
    healthStatus: "yellow",
    healthLabel: "Moderate",
    lastActive: "Met 3 weeks ago",
    foundingTaken: 6,
    foundingTotal: 20,
    timeOfDay: "evening",
  },
  {
    name: "Tirupati Sketchers",
    category: "Art",
    emoji: "🎨",
    bgColor: "#e8f5e9",
    shortDesc: "Urban sketching and watercolour sessions across Tirupati's temples and streets.",
    fullDesc: "Bring your sketchbook and discover the city through art. We sketch temples, streets, markets, and nature spots. All mediums welcome — pencil, ink, watercolour, digital. Monthly exhibitions at local cafes.",
    organizerName: "Kiran Mohan",
    organizerYears: "1 year running",
    organizerAvatar: "👨‍🎨",
    organizerResponse: "Responds within 12 hrs",
    memberCount: 22,
    schedule: "2nd & 4th Sunday, 9:00 AM",
    location: "TTD Kalyanamastu",
    activeSince: "2024",
    whatsappNumber: "919000000007",
    healthStatus: "red",
    healthLabel: "Quiet",
    lastActive: "Met 1 month ago",
    foundingTaken: 4,
    foundingTotal: 20,
    timeOfDay: "weekends",
  },
];

export async function seedDatabase() {
  try {
    const existing = await db.select().from(clubs);
    if (existing.length > 0) {
      log("Database already seeded, skipping...", "seed");
      return;
    }

    await db.insert(clubs).values(SEED_CLUBS);
    log(`Seeded ${SEED_CLUBS.length} clubs`, "seed");
  } catch (err) {
    console.error("Error seeding database:", err);
  }
}
